version: '3.4'

services:
  dockercontainer_kafka_demo:
    image: dockercontainerkafkademo:dev
    container_name: DockerContainer_Kafka_Demo
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DockerContainer_Kafka_Demo"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\Samsung\Documents\Gianluca\Git_Sources\.NetSamples\DockerContainer_Kafka_Demo\DockerContainer_Kafka_Demo:/app
      - C:\Users\Samsung\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Samsung\.nuget\packages\:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/DockerContainer_Kafka_Demo.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true